name: Update README all day at 04:04

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "03 4 * * *"

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update README.md file
        run: |
          node update_readme.js > README.md
        env:
          CI: true
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: DopeCloudd
          author_email: cloudd2vi@gmail.com
          message: ":memo: README.md updated by Commibot"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
